import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, NgForm } from '@angular/forms';
import { InvoiceFormInput } from '../../../models/invoice-form-input.model';
import { DataBaseService } from '../../../services/data-base.service';
import { Invoice } from '../../../models/invoice.model';

@Component({
  selector: 'app-new-insurance',
  imports: [
    CommonModule,
    FormsModule
  ],
  templateUrl: './new-insurance.component.html',
  styleUrl: './new-insurance.component.scss',
})
export class NewInsuranceComponent {

  /**
   * Instance of DataBaseService to access the Firebase Database.
   * @type {DataBaseService}
   */
  dataBaseService: DataBaseService = inject(DataBaseService);

  /**
   * The new invoice that is being created.
   * @type {InvoiceFormInput}
   */
  newInvoice: InvoiceFormInput = {
    type: '',
    //date: '',
    patient: ''
  };

  convertInvoiceFormInputToInvoice(invoiceFormInput: InvoiceFormInput): Invoice {
    return {
      id: '', // NOTE: will be generated by Firebase.
      type: invoiceFormInput.type,
      //date: new Date(invoiceFormInput.date),
      patient: invoiceFormInput.patient
    }
  }

  async onSubmit(form: NgForm): Promise<void> {
    if (form.invalid) {
      return;
    }
    const invoiceToSave = this.convertInvoiceFormInputToInvoice(this.newInvoice);
    try {
      await this.dataBaseService.addData<Invoice>('invoices', invoiceToSave);
      console.log('data added');
    } catch (error: any) {
      console.log('error');
    }

  }



}
